version: '3'


networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
    driver: local

services:
  arm_webserver:
    image: nginx:stable-alpine
    container_name: arm_webserver
    restart: unless-stopped
    tty: true
    ports:
      - "8090:80"
    volumes:
      - ./:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - arm_app
      - arm_mysql
    networks:
      - app-network

  arm_mysql:
    image: mysql:5.7.22
    container_name: arm_mysql
    restart: unless-stopped
    tty: true
    ports:
      - "3310:3306"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: arm
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql/
      - ./mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - app-network

  arm_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: arm_app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - app-network

  arm_composer:
    image: composer:latest
    container_name: arm_composer
    volumes:
      - ./:/var/www
    working_dir: /var/www
    depends_on:
      - arm_app
    networks:
      - app-network
